return {
    -- Spawner
    MIN_TIER = 1,
    MAX_TIER = math.huge,
    SPAWN_TIER_SCALING_DIVISOR = 10,

    -- Play Area
    AREA_WIDTH = 550,
    AREA_HEIGHT = 600,

    -- Physics
    ELASTICITY = 0.7,
    FRICTION = 0.0016,
    BASE_WEIGHT = 60,

    -- Dragging
    DRAG_ROTATION_MULTIPLIER = 5,
    DRAG_VELOCITY_MULTIPLIER = 0.025,
    DRAGGING_MAX_TILT = 15,
    BASE_DRAGGING_TILT_SPEED = 1,
    FREE_ROTATION_VELOCITY_DIVISOR = 3.5,
    DRAGGED_BOX_ALPHA = 0.8,

    -- Merge
    BASE_MERGE_SPEED = 400,
    BASE_MERGE_RANGE = 150,
    VELOCITY_MERGE_DURATION_FACTOR = 1,

    -- Animation
    SPAWN_SCALE_MULTIPLIER = 1.25,
    BASE_SCALE_TWEEN_DURATION = 0.3,
    WEIGHT_ANIM_DURATION_DIVISOR = 100,

    -- Object
    BASE_BOX_ZINDEX = 2
}
