return {
    DRAG_ROTATION_MULTIPLIER = 5,
    DRAG_VELOCITY_MULTIPLIER = 0.025,

    SPAWN_SCALE_MULTIPLIER = 1.25,

    BASE_SCALE_TWEEN_DURATION = 0.3,

    BASE_BOX_ZINDEX = 2,

    BASE_DRAGGING_TILT_SPEED = 1,
    BASE_MERGE_SPEED = 400,
    BASE_MERGE_RANGE = 150,
    BASE_WEIGHT = 60,

    FREE_ROTATION_VELOCITY_DIVISOR = 3.5,
    WEIGHT_ANIM_DURATION_DIVISOR = 100,
    SPAWN_TIER_SCALING_DIVISOR = 10,

    VELOCITY_MERGE_DURATION_FACTOR = 1,

    DRAGGING_MAX_TILT = 15,

    MAX_TIER = math.huge,
    MIN_TIER = 1,

    ELASTICITY = .7,
    FRICTION = .0016,

    AREA_WIDTH = 550,
    AREA_HEIGHT = 600,

    DRAGGED_BOX_ALPHA = .8
}
