-- ~/code/game/shop/constants.lua

return {
    UPGRADE_SHOP_UNLOCK_REQUIREMENT = 5,

    BLACK_MARKET_SELLING_REQUIREMENT = 15,
    BLACK_MARKET_BUYING_REQUIREMENT = 10,
    
    SACRIFICE_UNLOCK_REQUIREMENT = 20
}