-- ~/code/game/ui/constants.lua

local BOX_CONSTANTS = require("code.game.box.constants")

local SETTINGS_BUTTON_OFFSET = 35

return {
    RESET_BUTTON_WARN_TIME_OUT = .5,

    TEXT_BOX_FIRST_ERASE_COOLDOWN = .2,
    TEXT_BOX_ERASE_COOLDOWN = .05,

    BUTTON_Y_OFFSET = 100,
    SPAWN_BUTTON_Y = 475,
    NEW_GAME_BUTTON_Y = 375,
    TEMPLATE_SAVE_FILE_SLOT_OFFSET = 325,
    TEMPLATE_SAVE_FILE_Y_DIVIDER = 1.6,
    TEMPLATE_RESET_BUTTON_OFFSET = 10,
    TEMPLATE_LOAD_BUTTON_OFFSET = 60,
    TEMPLATE_ROTATION = math.rad(90),
    TEMPLATE_SCALE_X = 1.5,
    TEMPLATE_SCALE_Y = 2,
    TEMPLATE_SMALL_SCALE = 0.55,
    SETTINGS_BUTTON_OFFSET = SETTINGS_BUTTON_OFFSET,
    SETTINGS_BUTTON_X =  _G.WINDOW_WIDTH - SETTINGS_BUTTON_OFFSET,

    DEFAULT_BUTTON_PATH = "assets/sprites/ui/button220x75.png",
    STANBERRY_FONT_PATH = "assets/fonts/Stanberry.ttf",

    MIDDLE_X = _G.WINDOW_WIDTH / 2,
    MIDDLE_Y = _G.WINDOW_HEIGHT / 2,

    SPAWN_BUTTON_X = BOX_CONSTANTS.AREA_WIDTH + (_G.WINDOW_WIDTH - BOX_CONSTANTS.AREA_WIDTH) / 2,
}