-- ~/code/game/ui/constants.lua

local BOX_CONSTANTS = require("code.game.box.constants")
local CONSTANTS = {}

-- GENERAL BUTTON SETTINGS
CONSTANTS.BUTTON_Y_OFFSET = 100
CONSTANTS.DEFAULT_BUTTON_PATH = "assets/sprites/ui/button220x75.png"

-- FONT SETTINGS
CONSTANTS.STANBERRY_FONT_PATH = "assets/fonts/Stanberry.ttf"

-- WINDOW CENTER
CONSTANTS.MIDDLE_X = _G.WINDOW_WIDTH / 2
CONSTANTS.MIDDLE_Y = _G.WINDOW_HEIGHT / 2

-- SPAWN BUTTON POSITION
CONSTANTS.SPAWN_BUTTON_X = BOX_CONSTANTS.AREA_WIDTH + (_G.WINDOW_WIDTH - BOX_CONSTANTS.AREA_WIDTH) / 2
CONSTANTS.SPAWN_BUTTON_Y = 475

-- SETTINGS BUTTON
CONSTANTS.SETTINGS_BUTTON_OFFSET = 35
CONSTANTS.SETTINGS_BUTTON_X = _G.WINDOW_WIDTH - CONSTANTS.SETTINGS_BUTTON_OFFSET
CONSTANTS.SETTINGS_BUTTON_Y = CONSTANTS.SETTINGS_BUTTON_OFFSET

-- MAIN MENU OFFSETS
CONSTANTS.MAIN_MENU_NEW_GAME_BUTTON_Y = 375
CONSTANTS.MAIN_MENU_LOGO_PRIMARY_Y_OFFSET = 225
CONSTANTS.MAIN_MENU_LOGO_SECONDARY_Y_OFFSET = 100

-- SAVE FILE TEMPLATE OFFSETS
CONSTANTS.TEMPLATE_SAVE_FILE_SLOT_OFFSET = 325
CONSTANTS.TEMPLATE_SAVE_FILE_Y_DIVIDER = 1.6
CONSTANTS.TEMPLATE_LOAD_BUTTON_OFFSET = 60
CONSTANTS.TEMPLATE_RESET_BUTTON_OFFSET = 10
CONSTANTS.TEMPLATE_ROTATION = math.rad(90)
CONSTANTS.TEMPLATE_SCALE_X = 1.5
CONSTANTS.TEMPLATE_SCALE_Y = 2
CONSTANTS.TEMPLATE_SMALL_SCALE = 0.55
CONSTANTS.TEMPLATE_PREVIEW_OFFSET_Y = 25

-- SHOPKEEPER DEFAULT POSITION & SCALE
CONSTANTS.SHOPKEEPER_DEFAULT_X = 300
CONSTANTS.SHOPKEEPER_DEFAULT_Y = 300
CONSTANTS.SHOPKEEPER_SCALE_X = 2
CONSTANTS.SHOPKEEPER_SCALE_Y = 2

-- SIDEBAR AND UI BUTTON SPACING
CONSTANTS.BACK_BUTTON_X_OFFSET = 55
CONSTANTS.BUTTON_ROW_OFFSET = 75

-- TIME/COOLDOWN CONSTANTS
CONSTANTS.RESET_BUTTON_WARN_TIME_OUT = 0.5
CONSTANTS.TEXT_BOX_FIRST_ERASE_COOLDOWN = 0.2
CONSTANTS.TEXT_BOX_ERASE_COOLDOWN = 0.05

return CONSTANTS